# Generated by Django 5.2.6 on 2025-10-24 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='precio_unitario',
        ),
    ]
