# Generated by Django 5.2.6 on 2025-10-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiageneral',
            options={'verbose_name': 'Formato: Historia General (Pág. 9)', 'verbose_name_plural': 'Formatos: Historias Generales (Pág. 9)'},
        ),
        migrations.AlterModelOptions(
            name='historialmedico',
            options={'ordering': ['-fecha'], 'verbose_name': 'Historial (Contenedor)', 'verbose_name_plural': 'Historiales (Contenedores)'},
        ),
        migrations.AlterModelOptions(
            name='historianutricion',
            options={'verbose_name': 'Formato: Historia de Nutrición (Pág. 1 y 3)', 'verbose_name_plural': 'Formatos: Historias de Nutrición (Pág. 1 y 3)'},
        ),
        migrations.RemoveField(
            model_name='historiageneral',
            name='antecedentes_familiares',
        ),
        migrations.RemoveField(
            model_name='historiageneral',
            name='antecedentes_personales',
        ),
        migrations.RemoveField(
            model_name='historiageneral',
            name='enfermedad_actual',
        ),
        migrations.RemoveField(
            model_name='historianutricion',
            name='frec_dulces_lista4',
        ),
        migrations.AddField(
            model_name='historiageneral',
            name='antf_cardiovascular',
            field=models.BooleanField(default=False, verbose_name='Cardiovascular (Fam.)'),
        ),
        migrations.AddField(
            model_name='historiageneral',
            name='antf_diabetes',
            field=models.BooleanField(default=False, verbose_name='Diabetes (Fam.)'),
        ),
        migrations.AddField(
            model_name='historiageneral',
            name='antf_hepatitis',
            field=models.BooleanField(default=False, verbose_name='Hepatitis (Fam.)'),
        ),
        migrations.AddField(
            model_name='historiageneral',
            name='antf_neurologica',
            field=models.BooleanField(default=False, verbose_name='Neurológica (Fam.)'),
        ),
        migrations.AddField(
            model_name='historiageneral',
            name='antf_otros',
            field=models.TextField(blank=True, null=True, verbose_name='Otros Antecedentes Familiares'),
        ),
        migrations.AddField(
            model_name='historiageneral',
            name='antf_respiratoria',
            field=models.BooleanField(default=False, verbose_name='Respiratoria (Fam.)'),
        ),
        migrations.AddField(
            model_name='historiageneral',
            name='antp_alergias',
            field=models.BooleanField(default=False, verbose_name='Alergias (Pers.)'),
        ),
        migrations.AddField(
            model_name='historiageneral',
            name='antp_cardiovascular',
            field=models.BooleanField(default=False, verbose_name='Cardiovascular (Pers.)'),
        ),
        migrations.AddField(
            model_name='historiageneral',
            name='antp_cirugia',
            field=models.BooleanField(default=False, verbose_name='Cirugía (Pers.)'),
        ),
        migrations.AddField(
            model_name='historiageneral',
            name='antp_diabetes',
            field=models.BooleanField(default=False, verbose_name='Diabetes (Pers.)'),
        ),
        migrations.AddField(
            model_name='historiageneral',
            name='antp_habitos',
            field=models.BooleanField(default=False, verbose_name='Hábitos (Pers.)'),
        ),
        migrations.AddField(
            model_name='historiageneral',
            name='antp_hepatitis',
            field=models.BooleanField(default=False, verbose_name='Hepatitis (Pers.)'),
        ),
        migrations.AddField(
            model_name='historiageneral',
            name='antp_its',
            field=models.BooleanField(default=False, verbose_name='ITS (Pers.)'),
        ),
        migrations.AddField(
            model_name='historiageneral',
            name='antp_neurologica',
            field=models.BooleanField(default=False, verbose_name='Neurológica (Pers.)'),
        ),
        migrations.AddField(
            model_name='historiageneral',
            name='antp_osteomusculares',
            field=models.BooleanField(default=False, verbose_name='Osteomusculares (Pers.)'),
        ),
        migrations.AddField(
            model_name='historiageneral',
            name='antp_otros',
            field=models.TextField(blank=True, null=True, verbose_name='Otros Antecedentes Personales'),
        ),
        migrations.AddField(
            model_name='historiageneral',
            name='antp_respiratoria',
            field=models.BooleanField(default=False, verbose_name='Respiratoria (Pers.)'),
        ),
        migrations.AddField(
            model_name='historiageneral',
            name='ceca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='C.E.C.A.'),
        ),
        migrations.AddField(
            model_name='historiageneral',
            name='enfermero_nombre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Enfermero/a'),
        ),
        migrations.AddField(
            model_name='historiageneral',
            name='hea',
            field=models.TextField(blank=True, null=True, verbose_name='Historia Epidemiológica y Ambiental (HEA)'),
        ),
        migrations.AddField(
            model_name='historiageneral',
            name='tipo_afiliado',
            field=models.CharField(blank=True, choices=[('ADM', 'Administrativo'), ('OBR', 'Obrero'), ('DOC', 'Docente'), ('EST', 'Estudiante'), ('FAM', 'Familiar')], max_length=3, null=True, verbose_name='Tipo de Afiliado'),
        ),
        migrations.AddField(
            model_name='historianutricion',
            name='frec_dulces',
            field=models.CharField(blank=True, choices=[('', '---------'), ('D', 'Diario'), ('S', 'Semanal'), ('M', 'Mensual'), ('O', 'Ocasional'), ('N', 'Nunca')], max_length=2, null=True, verbose_name='Dulces'),
        ),
        migrations.AlterField(
            model_name='historianutricion',
            name='antf_otros',
            field=models.TextField(blank=True, null=True, verbose_name='Otros Antecedentes Familiares (Nutri)'),
        ),
        migrations.AlterField(
            model_name='historianutricion',
            name='antp_otros',
            field=models.TextField(blank=True, null=True, verbose_name='Otros Antecedentes Personales (Nutri)'),
        ),
        migrations.AlterField(
            model_name='historianutricion',
            name='ceca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='C.E.C.A. (Nutrición)'),
        ),
        migrations.AlterField(
            model_name='historianutricion',
            name='mencion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mención (Nutrición)'),
        ),
        migrations.AlterField(
            model_name='historianutricion',
            name='semestre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Semestre (Nutrición)'),
        ),
    ]
