# Generated by Django 5.2.6 on 2025-10-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historiales', '0002_alter_historiageneral_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historianutricion',
            old_name='antf_cancer',
            new_name='antf_nutri_cancer',
        ),
        migrations.RenameField(
            model_name='historianutricion',
            old_name='antf_cardiopatias',
            new_name='antf_nutri_cardiopatias',
        ),
        migrations.RenameField(
            model_name='historianutricion',
            old_name='antf_diabetes',
            new_name='antf_nutri_diabetes',
        ),
        migrations.RenameField(
            model_name='historianutricion',
            old_name='antf_gastritis',
            new_name='antf_nutri_gastritis',
        ),
        migrations.RenameField(
            model_name='historianutricion',
            old_name='antf_hipertiroidismo',
            new_name='antf_nutri_hipertiroidismo',
        ),
        migrations.RenameField(
            model_name='historianutricion',
            old_name='antf_hipotiroidismo',
            new_name='antf_nutri_hipotiroidismo',
        ),
        migrations.RenameField(
            model_name='historianutricion',
            old_name='antf_hta',
            new_name='antf_nutri_hta',
        ),
        migrations.RenameField(
            model_name='historianutricion',
            old_name='antf_otros',
            new_name='antf_nutri_otros',
        ),
        migrations.RenameField(
            model_name='historianutricion',
            old_name='antp_cancer',
            new_name='antp_nutri_cancer',
        ),
        migrations.RenameField(
            model_name='historianutricion',
            old_name='antp_cardiopatias',
            new_name='antp_nutri_cardiopatias',
        ),
        migrations.RenameField(
            model_name='historianutricion',
            old_name='antp_diabetes',
            new_name='antp_nutri_diabetes',
        ),
        migrations.RenameField(
            model_name='historianutricion',
            old_name='antp_gastritis',
            new_name='antp_nutri_gastritis',
        ),
        migrations.RenameField(
            model_name='historianutricion',
            old_name='antp_hipertiroidismo',
            new_name='antp_nutri_hipertiroidismo',
        ),
        migrations.RenameField(
            model_name='historianutricion',
            old_name='antp_hipotiroidismo',
            new_name='antp_nutri_hipotiroidismo',
        ),
        migrations.RenameField(
            model_name='historianutricion',
            old_name='antp_hta',
            new_name='antp_nutri_hta',
        ),
        migrations.RenameField(
            model_name='historianutricion',
            old_name='antp_otros',
            new_name='antp_nutri_otros',
        ),
    ]
