# Generated by Django 5.2.6 on 2025-10-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiales', '0002_alergia_enfermedad_alter_historialmedico_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmedico',
            name='enfermedades_preexistentes',
            field=models.ManyToManyField(blank=True, related_name='historiales', to='historiales.enfermedad', verbose_name='Antecedentes Personales'),
        ),
    ]
