# Generated by Django 5.2.6 on 2025-10-25 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiales', '0003_alter_historialmedico_enfermedades_preexistentes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmedico',
            name='medico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='historiales_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
