# Generated by Django 5.2.6 on 2025-10-28 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historiales', '0003_rename_antf_cancer_historianutricion_antf_nutri_cancer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentoreferencia',
            name='motivo_referencia',
        ),
    ]
