# Generated by Django 5.2.6 on 2025-10-25 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiales', '0004_historialmedico_medico'),
        ('pacientes', '0007_alter_paciente_apellido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmedico',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historialmedico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='pacientes.paciente'),
        ),
    ]
