# Generated by Django 5.2.6 on 2025-10-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiales', '0004_remove_documentoreferencia_motivo_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoreferencia',
            name='referido_a',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Referido a Consulta'),
        ),
    ]
