# Generated by Django 5.2.6 on 2025-10-28 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historiales', '0006_truncate_referido_a'),
    ]

    operations = [
    ]
