# Generated by Django 5.2.6 on 2025-10-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiales', '0007_truncate_recipe_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentorecipe',
            name='texto_recipe',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Récipe / Indicaciones'),
        ),
    ]
