# Generated by Django 5.2.6 on 2025-10-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiales', '0008_alter_documentorecipe_texto_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historianutricion',
            name='empleo',
        ),
        migrations.RemoveField(
            model_name='historianutricion',
            name='estado_civil',
        ),
        migrations.AddField(
            model_name='historianutricion',
            name='es_empleado',
            field=models.BooleanField(default=False, verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='historianutricion',
            name='es_estudiante',
            field=models.BooleanField(default=False, verbose_name='Est.'),
        ),
    ]
