# Generated by Django 5.2.6 on 2025-10-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiales', '0009_remove_historianutricion_empleo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historianutricion',
            options={'verbose_name': 'Formato: Historia de Nutrición', 'verbose_name_plural': 'Formatos: Historias de Nutrición'},
        ),
        migrations.RemoveField(
            model_name='historianutricion',
            name='tabla_antropometrica',
        ),
        migrations.AddField(
            model_name='historianutricion',
            name='antropo_ag',
            field=models.FloatField(blank=True, null=True, verbose_name='AG'),
        ),
        migrations.AddField(
            model_name='historianutricion',
            name='antropo_am',
            field=models.FloatField(blank=True, null=True, verbose_name='AM'),
        ),
        migrations.AddField(
            model_name='historianutricion',
            name='antropo_circ_brazo',
            field=models.FloatField(blank=True, null=True, verbose_name='C. Brazo'),
        ),
        migrations.AddField(
            model_name='historianutricion',
            name='antropo_circ_cadera',
            field=models.FloatField(blank=True, null=True, verbose_name='C. Cadera'),
        ),
        migrations.AddField(
            model_name='historianutricion',
            name='antropo_circ_cintura',
            field=models.FloatField(blank=True, null=True, verbose_name='C. Cintura'),
        ),
        migrations.AddField(
            model_name='historianutricion',
            name='antropo_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='historianutricion',
            name='antropo_imc',
            field=models.FloatField(blank=True, null=True, verbose_name='IMC'),
        ),
        migrations.AddField(
            model_name='historianutricion',
            name='antropo_pliegue_abdominal',
            field=models.FloatField(blank=True, null=True, verbose_name='Pliegue Abdominal'),
        ),
        migrations.AddField(
            model_name='historianutricion',
            name='antropo_pliegue_muslo_anterior',
            field=models.FloatField(blank=True, null=True, verbose_name='Pliegue Muslo Anterior'),
        ),
        migrations.AddField(
            model_name='historianutricion',
            name='antropo_pliegue_pantorrilla',
            field=models.FloatField(blank=True, null=True, verbose_name='Pliegue Pantorrilla'),
        ),
        migrations.AddField(
            model_name='historianutricion',
            name='antropo_pliegue_subescapular',
            field=models.FloatField(blank=True, null=True, verbose_name='Pliegue Subescapular'),
        ),
        migrations.AddField(
            model_name='historianutricion',
            name='antropo_pliegue_suprailiaco',
            field=models.FloatField(blank=True, null=True, verbose_name='Pliegue Suprailíaco'),
        ),
        migrations.AddField(
            model_name='historianutricion',
            name='antropo_pliegue_triceps',
            field=models.FloatField(blank=True, null=True, verbose_name='Pliegue Tríceps'),
        ),
        migrations.AddField(
            model_name='historianutricion',
            name='antropo_suma_pliegues',
            field=models.FloatField(blank=True, null=True, verbose_name='Σ Pliegues'),
        ),
        migrations.AddField(
            model_name='historianutricion',
            name='antropo_talla',
            field=models.FloatField(blank=True, null=True, verbose_name='Talla (cm)'),
        ),
        migrations.AddField(
            model_name='historianutricion',
            name='req_a',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='A'),
        ),
        migrations.AddField(
            model_name='historianutricion',
            name='req_c',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='C'),
        ),
        migrations.AddField(
            model_name='historianutricion',
            name='req_f',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='F'),
        ),
        migrations.AddField(
            model_name='historianutricion',
            name='req_g',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='G'),
        ),
        migrations.AddField(
            model_name='historianutricion',
            name='req_l',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='L'),
        ),
        migrations.AddField(
            model_name='historianutricion',
            name='req_v',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='V'),
        ),
        migrations.AlterField(
            model_name='historianutricion',
            name='alim_hidricos_vasos_dia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hídricos: Vasos/día'),
        ),
        migrations.AlterField(
            model_name='historianutricion',
            name='frec_dulces_otros',
            field=models.CharField(blank=True, choices=[('', '---------'), ('D', 'Diario'), ('S', 'Semanal'), ('M', 'Mensual'), ('O', 'Ocasional'), ('N', 'Nunca')], max_length=2, null=True, verbose_name='Dulces'),
        ),
        migrations.AlterField(
            model_name='historianutricion',
            name='func_masticacion',
            field=models.BooleanField(default=False, verbose_name='Masticación'),
        ),
        migrations.AlterField(
            model_name='historianutricion',
            name='func_periodos_menstruales',
            field=models.BooleanField(default=False, verbose_name='Períodos Menstruales'),
        ),
    ]
